### ISSUE TITLE
Different SHA256 hash at Client Handshake finished

### ISSUE THREAD

**Issue by KevinAdhaikal** [syncsynchalt/illustrated-tls#24]
Hello, when I try to hash 256 of all messages (Client Hello, Server Hello, Server Certificate, Server Key Exchange, Server Hello Done, Client Key Exchange)

the resulting hash was: 3ca71a43de9adc6f246a03715bed8c2ec3a8416b432a9e43f09147298336814f
but, on the website it: 061dda04b3c2217ff73bd79b9cf88a2bb6ec505404aac8722db03ef417b54cb4

```
#include <stdio.h>
#include <stdlib.h>
#include "libtomcrypt/src/headers/tomcrypt.h"

void print_hex(unsigned char* data, int len) {
    for (int i = 0; i < len; i++) {
        printf("%02x", data[i]);
    }
    printf("\n");
}

int main(int argc, char *argv[]) {
    if (argc != 2) {
        printf("Usage: %s <filename>\n", argv[0]);
        return 1;
    }

    const char *filename = argv[1];
    FILE *file = fopen(filename, "rb");
    if (!file) {
        perror("Failed to open file");
        return 1;
    }

    hash_state sha256;
    unsigned char hash[32];
    unsigned char buffer;
    size_t read;

    sha256_init(&sha256);

    while ((read = fread(&buffer, 1, sizeof(buffer), file)) > 0) {
        sha256_process(&sha256, &buffer, read);
    }

    sha256_done(&sha256, hash);

    printf("SHA256 hash of %s: ", filename);
    print_hex(hash, sizeof(hash));

    fclose(file);
    return 0;
}
```

Is my code wrong or not?

**Comment by KevinAdhaikal** [comment]
https://www.mediafire.com/file/gkz36r2gwp9ioj1/total.bin/file

this is the file that I hash.
is there anything missing bytes in my file?

**Comment by syncsynchalt** [comment]
Hi Kevin, thanks for reaching out!

I have a suspicion of what's going on here, and the thing that's tipping me off is the word "payload" in this sentence:

> The verify_data is built from the master secret and the hash of the _payload_ of all handshake records (type=0x16) previous to this one.

I bet that this means the 5-byte header of each record should be stripped off.  Just tested it, and yes that seems to fix it.  I'm using `tail -c +6` to strip off the leading 5 bytes of each file in this test:

```
tail -c +6 clienthello > test.bin
tail -c +6 serverhello >> test.bin
tail -c +6 servercert >> test.bin
tail -c +6 serverkeyexchange >> test.bin
tail -c +6 serverhellodone >> test.bin
tail -c +6 clientkeyexchange >> test.bin
openssl sha256 test.bin

SHA2-256(test.bin)= 061dda04b3c2217ff73bd79b9cf88a2bb6ec505404aac8722db03ef417b54cb4
```

Thanks by the way for providing code and file to make this easy to catch up on my side.

As an aside: you're looking at the TLS 1.2 page, which I did first and which isn't as good about repeatability as the later pages like the one for TLS 1.3.  In those pages I tend to show exactly how I came up with the starting hashes, instead of just declaring their value.  I'm going to leave this issue open and add in some code samples to show how to get each hash value, hopefully that'll save people some time down the line.

I also noticed that the TLS 1.2 site closes each record when you click anywhere in it, that sure is annoying and makes the site hard to read! It's not intended, I must have backported something from the later sites and it's going haywire here.  I'll look at fixing that too.

**Comment by syncsynchalt** [comment]
This should be fixed now, you may need to force-refresh your browser to get an updated `index.html`.

Please note three things for the later "Server Handshake Finished" hash calculation, when you get there:
- that hash includes the "client finished" record, which the client didn't use in its hash because it hasn't sent it yet
- that hash includes the _decrypted_ data of the "client finished" record, unlike all other handshake records (which were sent without encryption)
- the repo had a bad version of the `captures/caps/clientfinishedplain` file, with some garbage data from the decryption process appended. Make sure to pull a fresh copy of this repo if you're using the files from it in your testing/reproduction.

Let me know if you run into further problems like this, while I'll probably never go back and re-do the whole TLS 1.2 site to bring it up to par with the later sites I'd still like to improve it when people hit a wall like you did.

**Comment by KevinAdhaikal** [comment]
Thanks!
